FROM node:12.16.1-alpine3.11

# Create app directory
RUN mkdir -p /usr/src/app && chown -R node:node /usr/src/app
WORKDIR /usr/src/app

COPY package*.json babel.config.js ./

RUN npm install

COPY ./src ./src

COPY ./public ./public


RUN npm run build

RUN npm prune --production # Remove dev dependencies

CMD [ "npm", "run", "start" ]